name: Check Code Style - FLAKE8

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install Dependencies
        run: |
          # These packages are installed in the base environment but may be older
          # versions. Explicitly upgrade them because they often create
          # installation problems if out of date.
          python -m pip install --upgrade

          pip install pylint
      - name: Run flake8
        run: |
          # always pass this so we get the report without failing CI
          # eventually remove --exit-zero
          pylint tid --exit-zero
